apiVersion: v1
kind: Job
metadata:
  name: math-add-job
spec:

  # creates 3 pods to run job
  completions: 3

  # creates containers in parallel instead of sequentially
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']

      restartPolicy: Never