apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    # labels of RS (only one needed, )
    app: myapp
    # type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      # labels of pods 
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-containter
          image: nginx
  replicas: 3
  selector:
    # if pod labels match, RS labels based on selector, RS creates successfully
    matchLabels:
      app: myapp
