apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-vol1
spec: 
  accessModes:
    - ReadWriteOnce
    # ReadOnlyMany
    # ReadWriteMany
  
  capacity:
    storage: 1Gi
  
  # not to used in production env
  hostPath:
    path: /tmp/data

  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
    