apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
    - args:
      - /bin/sh
      - -c
      - wget -O /work-dir/index.html http://neverssl.com/online      
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - name: vol1
          mountPath: /work-dir
  conatianers:
  - image: nginx
    name: nginx
    ports:
    - conatinerPort: 80
   
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
