# clusters
# context
# users

apiVersion: v1
kind: Config

current-context: dev-user@google

clusters:
  - name: my-kube-playground
    cluster: 
      certificate-authority: /etc/kubernetes/pki/ca.crt
      certificate-authority-data: <base64-encoded-cert>
      server: https://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playground
  - name: dev-user@google
  - name: prod-user@production

users:
- name: my-kube-admin
- name: admin
- name: dev-user
- name: prod-user